const moviesActionTypes = {
	SET_IS_SEARCHING: "SET_IS_SEARCHING",
	SET_SEARCH_QUERY: "SET_SEARCH_QUERY",
	SET_SHOW_DETAILS: "SET_SHOW_DETAILS",
	SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
	SET_SELECTED_MOVIE: "SET_SELECTED_MOVIE",
	SET_IS_LOADING_DETAILS: "SET_IS_LOADING_DETAILS",
	SET_MOVIE_DETAILS: "SET_MOVIE_DETAILS",
};

export default moviesActionTypes;
